/**
 * Release truth for the website download matrix.
 *
 * GENERATED by scripts/generate-site-releases.mjs from real GitHub Release assets.
 * Do not hand-edit: a platform is only `verified` when its file actually exists.
 */
export type ReleaseStatus = "verified" | "building" | "planned";

export type ReleaseAsset = {
  os: string;
  arch: string;
  packageName: string;
  status: ReleaseStatus;
  url: string | null;
};

export type ReleaseInfo = {
  version: string;
  actionsUrl: string;
  assets: ReleaseAsset[];
};

export const releases: ReleaseInfo = {
  "version": "0.3.0",
  "actionsUrl": "https://github.com/ambartsumov/turkmenai-local/actions",
  "assets": [
    {
      "os": "Linux",
      "arch": "x64",
      "packageName": "AppImage",
      "status": "verified",
      "url": "https://github.com/ambartsumov/turkmenai-local/releases/download/v0.3.0/TurkmenAI-Local-Linux-x64.AppImage"
    },
    {
      "os": "Debian / Ubuntu",
      "arch": "x64",
      "packageName": "DEB",
      "status": "verified",
      "url": "https://github.com/ambartsumov/turkmenai-local/releases/download/v0.3.0/TurkmenAI-Local-Linux-x64.deb"
    },
    {
      "os": "Fedora / RHEL",
      "arch": "x64",
      "packageName": "RPM",
      "status": "verified",
      "url": "https://github.com/ambartsumov/turkmenai-local/releases/download/v0.3.0/TurkmenAI-Local-Linux-x64.rpm"
    },
    {
      "os": "Linux",
      "arch": "ARM64",
      "packageName": "AppImage",
      "status": "verified",
      "url": "https://github.com/ambartsumov/turkmenai-local/releases/download/v0.3.0/TurkmenAI-Local-Linux-arm64.AppImage"
    },
    {
      "os": "Windows 10 / 11",
      "arch": "x64",
      "packageName": "EXE (NSIS)",
      "status": "verified",
      "url": "https://github.com/ambartsumov/turkmenai-local/releases/download/v0.3.0/TurkmenAI-Local-Windows-x64.exe"
    },
    {
      "os": "Windows 10 / 11",
      "arch": "ARM64",
      "packageName": "EXE (NSIS)",
      "status": "verified",
      "url": "https://github.com/ambartsumov/turkmenai-local/releases/download/v0.3.0/TurkmenAI-Local-Windows-arm64.exe"
    },
    {
      "os": "macOS",
      "arch": "Apple Silicon",
      "packageName": "DMG",
      "status": "verified",
      "url": "https://github.com/ambartsumov/turkmenai-local/releases/download/v0.3.0/TurkmenAI-Local-macOS-arm64.dmg"
    },
    {
      "os": "macOS",
      "arch": "Intel x64",
      "packageName": "DMG",
      "status": "building",
      "url": null
    }
  ]
};
