/**
 * Release truth for the website download matrix.
 *
 * This file is the single source of truth for what is actually downloadable. It
 * is regenerated by `scripts/generate-site-releases.mjs` from the real GitHub
 * Release assets, so a platform is only ever marked `verified` when its file
 * exists. Never hand-edit a status to `verified` for a file that was not built.
 */
export type ReleaseStatus = "verified" | "building" | "planned";

export type ReleaseAsset = {
  os: string;
  arch: string;
  packageName: string;
  status: ReleaseStatus;
  /** Present only when status === "verified". */
  url: string | null;
};

export type ReleaseInfo = {
  version: string;
  /** GitHub Actions URL used for "building" targets. */
  actionsUrl: string;
  assets: ReleaseAsset[];
};

const RELEASE_BASE = "https://github.com/ambartsumov/turkmenai-local/releases/download";

// Current reality: the v0.1.0 pre-release published Linux x64 installers only.
// Windows/macOS/Linux-arm64 are configured in the CI matrix but not yet published,
// so they are shown as "building" (link to Actions) — never as a dead download.
export const releases: ReleaseInfo = {
  version: "0.1.0",
  actionsUrl: "https://github.com/ambartsumov/turkmenai-local/actions",
  assets: [
    { os: "Linux", arch: "x64", packageName: "AppImage", status: "verified", url: `${RELEASE_BASE}/v0.1.0/TurkmenAI-Local-Linux-x64.AppImage` },
    { os: "Debian / Ubuntu", arch: "x64", packageName: "DEB", status: "verified", url: `${RELEASE_BASE}/v0.1.0/TurkmenAI-Local-Linux-x64.deb` },
    { os: "Fedora / RHEL", arch: "x64", packageName: "RPM", status: "verified", url: `${RELEASE_BASE}/v0.1.0/TurkmenAI-Local-Linux-x64.rpm` },
    { os: "Linux", arch: "ARM64", packageName: "AppImage", status: "building", url: null },
    { os: "Windows 10 / 11", arch: "x64", packageName: "EXE (NSIS)", status: "building", url: null },
    { os: "Windows 10 / 11", arch: "ARM64", packageName: "EXE (NSIS)", status: "building", url: null },
    { os: "macOS", arch: "Apple Silicon", packageName: "DMG", status: "building", url: null },
    { os: "macOS", arch: "Intel x64", packageName: "DMG", status: "building", url: null },
  ],
};
